version: "3"

services:
  backend:
    build: backend
    restart: always
    ports:
      - 8088:8088
    container_name: backend

  frontend:
    build: frontend
    restart: always
    ports:
      - 3000:3000
    container_name: frontend


